### ISSUE TITLE
a flow diagram, visual schema or graph of RePEc

### ISSUE THREAD

**Issue by moqri** [repec-org/websites#2]
It would be nice to have a diagram/schema/graph to explain what is RePEc or to group the services

**Comment by moqri** [comment]
Kit said in an email: "Yes,   I think that sort of flow diagram would be very useful, and could simplify the presentation of the ancillary services. "

**Comment by moqri** [comment]
@r14160 (corrected) said in an email: "I think we should also do the following on the page:
A graph with RePEc in the center, arrows pointing into it from above with
a label like "intake" or "publishers", an arrow coming to RePEc from the
side with "enhancement" and arrows from RePEc to the bottom with
"dissemination". "

**Comment by r14160** [comment]
@r14160, not @chris

**Comment by moqri** [comment]
Moved to https://github.com/repec-org/repec.org/issues/1
